<?php
/**
 * @file
 * ALQ Shop customisations module.
 */

/**
 *
 * Implementation of hook_uc_checkout_pane()
 *
 */
function alq_shop_uc_checkout_pane() {
  return [
    [
      'id' => 'shipping_options',
      'title' => 'ALQ Shipping options',
      'desc' => 'Provide customers with the options for shipping',
      'callback' => 'alq_shop_pane_checkout',
      'process' => TRUE,
      'weight' => 1,
    ],
  ];
}


/**
 *
 * Checkout pane function
 *
 */
function alq_shop_pane_checkout($op, $arg1, $arg2) {
  // If no products are shippable, exit.
  if (!uc_cart_is_shippable()) {
    return;
  }

  switch ($op) {
    // Checkout form.
    case 'view':
      //Return all products in cart; run through list and total up cost of shippable items.
      $shipping_options = [
        'aus' => t('Deliver within Australia'),
        'pickup' => t('No delivery Pick up from ALQ Brisbane shop'),
        'int' => t('Deliver internationally'),
      ];

      $context = [
        'revision' => 'themed-original',
        'type' => 'shipping',
      ];

      $price = 22;

      $description = t("Please select your delivery preference?");

      $contents['shipping_cost'] = [
        '#markup' => 'Shipping cost: ' . uc_price($price, $context),
      ];

      $contents['shipping'] = [
        '#type' => 'radios',
        '#options' => $shipping_options,
        '#required' => TRUE,
        '#title' => t('Delivery options'),
        '#default_value' => $arg1->shipping_option ? $arg1->shipping_option : NULL,
      ];

      return [
        'description' => $description,
        'contents' => $contents
      ];

    // Checkout processing.
    case 'process':
      $arg1->shipping_option = [
        'option' => $arg2['option'],
        'cost' => $arg2['cost'],
      ];
      return TRUE;

    //CHECKOUT REVIEW
    case 'review':
      $message[0] = ['title' => t('Shipping Cost')];

      $message[0]['data'] = t('Accepted');
      $message[] = [
        'title' => 'Cost',
        'data' => '$' . $arg1->shipping_option['cost'],
      ];
      return $message;
  }
}


/**
 *
 * Implementation of hook_line_item
 *
 */
function alq_shop_line_item() {
  $items[] = [
    'id' => 'shipping_chost',
    'title' => t('Shipping cost'),
    'weight' => 2,
    'default' => TRUE,
    'stored' => TRUE,
    'add_list' => FALSE,
    'calculated' => TRUE,
    'display_only' => FALSE,
  ];

  return $items;
}