<?php

/**
 * @file
 * Provides blocks for the content type section home
 * initially the image display at the top and the list
 * of related links at the left.
 */

/**
 * Implements hook_block_info().
 */
function alq_section_home_blocks_block_info() {
  return array(
    "alq_section_home_header" => array(
      "info" => t("Section Home Header"),
    ),
    "alq_section_home_childtree" => array(
      "info" => t("Section Home childtree"),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function alq_section_home_blocks_block_view($delta = "") {
  $block = NULL;

  switch ($delta) {
    case "alq_section_home_header":
      $block["subject"] = t("Header Image");
      if (user_access("access content")) {
        $image = alq_section_home_blocks_get_image();
        $block["content"] = theme("alq_section_home_header", array("image" => $image));
      }
      break;

    case "alq_section_home_childtree":
      if (user_access("access content")) {
        $name = menu_get_active_title();
        if ($name) {
          $submenu = alq_section_home_blocks_get_childtree($name);

          if (count($submenu["childtree"]) > 0) {
            $block["subject"] = t("Topics");
            $block["content"] = theme("alq_section_home_childtree", array(
              "title" => $submenu["parent"],
              "childtree" => $submenu["childtree"],
            )
            );
          }
        }
      }
      break;
  }

  return $block;
}

/**
 * Implements hook_theme();.
 */
function alq_section_home_blocks_theme() {
  return array(
    "alq_section_home_header" => array(
      "template" => "theme/section-home-header",
      "variables" => array(
        "image" => NULL,
      ),
    ),
    "alq_section_home_childtree" => array(
      "template" => "theme/section-home-childtree",
      "variables" => array(
        "title" => NULL,
        "childtree" => NULL,
      ),
    ),
  );
}

/**
 * Return the image for the current node we are
 * viewing.
 *
 * @return mixed image path or false if no image
 */
function alq_section_home_blocks_get_image() {
  $node = menu_get_object();
  if (is_null($node)) {
    // Only the shop page at the moment so return.
    return drupal_get_path('theme', 'alq') . '/images/alq_shop_banner.jpg';
  }
  else {
    return count($node->field_image) ? $node->field_image[$node->language][0]["uri"] : FALSE;
  }
}

/**
 * Return the child images for the current node we are
 * viewing.
 */
function alq_section_home_blocks_get_childtree($name) {
  $tree = menu_tree_all_data('menu-header-menu');

  $childtree = array();
  $parent = "";

  foreach ($tree as $branch) {
    if (($branch['link']['title'] === $name) || _in_below($name, $branch['below'])) {
      $parent = $branch['link']['title'];
      $childtree = $branch['below'];
      break;
    }
  }

  return array(
    "childtree" => $childtree,
    "parent" => $parent,
  );
}

/**
 *
 */
function _in_below($needle, $haystack) {
  foreach ($haystack as $hay) {
    if ($hay['link']['title'] === $needle) {
      return TRUE;
    }
  }
  return FALSE;
}
