<?php
/**
 * @file
 * Provides blocks for the content type section home
 * initially the image display at the top and the list
 * of related links at the left
 */

/**
 * Implements hook_block_info().
 */
function alq_section_home_blocks_block_info() {
  return array(
    "alq_section_home_header" => array(
      "info" => t("Section Home Header"),
    ), 
    "alq_section_home_childtree" => array(
      "info" => t("Section Home childtree"),
    ), 
  ); 
}

/**
 * Implements hook_block_view().
 */
function alq_section_home_blocks_block_view($delta = "") {
  switch ($delta) {
    case "alq_section_home_header":
      $block["subject"] = t("Header Image");
      if (user_access("access content")) {
        $image = alq_section_home_blocks_get_image();
        $block["content"] = theme("alq_section_home_header", array("image" => $image));
      }
      break;
    case "alq_section_home_childtree":
      $block["subject"] = t("Topics");
      if (user_access("access content")) {
        $node = menu_get_object();
        $childtree = alq_section_home_blocks_get_childtree($node);
        $block["content"] = theme("alq_section_home_childtree", array(
            "title" => $node->title,
            "childtree" => $childtree
          )
        );
      }
      break;
  }

  return $block;
}

/**
 * Implements hook_theme();
 */
function alq_section_home_blocks_theme() {
  return array(
      "alq_section_home_header" => array(
        "template" => "theme/section-home-header",
        "variables" => array(
          "image" => null
        )
      ),
      "alq_section_home_childtree" => array(
        "template" => "theme/section-home-childtree",
        "variables" => array(
          "title" => null,
          "childtree" => null
        )
      ),
    );
}

/**
 * Return the image for the current node we are
 * viewing
 *
 * @return  mixed image path or false if no image
 */
function alq_section_home_blocks_get_image() {
  $node = menu_get_object();
  return count($node->field_image) ? $node->field_image[$node->language][0]["uri"] : false;
}

/**
 * Return the child images for the current node we are
 * viewing
 */
function alq_section_home_blocks_get_childtree($node) {
  $tree = menu_tree_all_data('menu-header-menu'); 

  $childtree = array();
  
  foreach ($tree as $branch){
    if ($branch['link']['title'] == $node->title){
      $childtree = $branch['below'];
      break;
    }
  }
  return $childtree;
}
