# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

aliases:
  - &cache_key v1-dependencies-{{ checksum "scripts/drush.make" }}-{{ checksum "composer.json" }}
  - &web_dir /var/www/html
  - &vcs_dir ~/project

defaults: &defaults
  docker:
    - image: circleci/php:7.2-apache-browsers
    - image: circleci/mysql:5.7
  working_directory: *vcs_dir

set_env: &set_env
  run:
    name: "Setup custom environment variables"
    command: |
      echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      echo 'export GIT_DIR="/home/circleci/project"' >> $BASH_ENV
      echo 'export ADMIN="testadmin"' >> $BASH_ENV
      echo 'export DB_FILE="/home/circleci/project/.circleci/data/test-data.sql.gz"' >> $BASH_ENV
      echo 'export DB_HOST="127.0.0.1"' >> $BASH_ENV
      echo 'export DB_NAME="circle_test"' >> $BASH_ENV
      echo 'export DB_USER="root"' >> $BASH_ENV
      echo 'export SITE_EMAIL="test@camerongreen.org"' >> $BASH_ENV
      echo 'export PATH=${PATH}:~circleci/project/vendor/bin' >> $BASH_ENV
      source $BASH_ENV

install_composer: &install_composer
  run:
    name: Install composer
    command: |
      php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      php composer-setup.php
      php -r "unlink('composer-setup.php');"
      sudo mv composer.phar /usr/local/bin/composer

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *set_env
      - restore_cache:
          keys:
            - *cache_key
      - run: mkdir ~/test-reports
      - run:
          name: Set up packages
          command: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install -y curl vim default-jre mariadb-client libpng-dev build-essential
            sudo docker-php-ext-install pdo_mysql && sudo docker-php-ext-install gd
      - run:
          # NPM doesn't have an apt package so install it manually.
          name: Install node and npm
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
            sudo apt-get install -y nodejs
      # Install mod_rewrite and start apache.
      - run: sudo a2enmod rewrite && sudo service apache2 start
      - *install_composer
      - run:
          name: Install composer dependencies
          command: |
            composer install --prefer-dist
      - run:
          name: Install site
          working_directory: *web_dir
          command: |
            sudo -E ~circleci/project/scripts/create_site.sh
      - run:
          name: Install database
          working_directory: *web_dir
          command: |
            sudo -E ~circleci/project/scripts/import_prod_db.sh
      - run: sudo chown -R www-data:www-data /var/www/html
      - run: cd test && ./run-tests.sh
      - save_cache:
          paths:
            - ~/project/.docker/config/vendor
            - ~/.composer/cache
          key: *cache_key

      # run tests!
      - store_artifacts:
          path: /tmp/screenshots
