# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2

aliases:
  &cache_key v1-dependencies-{{ checksum "scripts/drush.make" }}

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-browsers
      - image: circleci/mysql:5.7

    working_directory: ~/project

    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run:
          name: Set up packages.
          command: |
            sudo apt-get update && sudo apt-get upgrade
            sudo apt-get install -y curl vim default-jre mysql-client libpng-dev build-essential
      - run:
          name: Install extensions
          command: |
            sudo docker-php-ext-install pdo_mysql
            sudo docker-php-ext-install gd
      - run:
          name: Install mod_rewrite and start apache.
          command: |
            sudo a2enmod rewrite
            sudo service apache2 start
      - run:
          name: Install NPM.
          command: |
            sudo curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Composer and Composer Install.
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar self-update
            sudo mv composer.phar /usr/local/bin/composer
            sudo composer self-update
            cp .docker/config/composer.json .
            composer install --prefer-dist
      - run:
          name: Install site
          command: |
            cd /var/www/html && sudo -- sh -c "GIT_DIR=/home/circleci/project ADMIN=testadmin DB_USER=root DB_NAME=circle_test DB_HOST=127.0.0.1 CIRCLECI=1 SITE_EMAIL=test@camerongreen.org /home/circleci/project/scripts/create_site.sh"
            cd /var/www/html && sudo -- sh -c "DB_FILE=/home/circleci/project/.circleci/data/test-data.sql.gz DB_USER=root DB_NAME=circle_test DB_HOST=127.0.0.1 CIRCLECI=1 SITE_EMAIL=test@camerongreen.org /home/circleci/project/scripts/import_prod_db.sh"
            sudo chown -R www-data:www-data /var/www/html
      - save_cache:
          paths:
            - ./vendor
          key: *cache_key
      - run:
          name: Run tests!
          command: |
            mkdir test-reports
            cd test && ./run-tests.sh
      - store_artifacts:
          path: /tmp/screenshots
