# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      - image: circleci/mysql:latest

    working_directory: ~/

    steps:
      - checkout

      - run: sudo apt install composer

      - run: composer install -n --prefer-dist

      - run: DB_PASSWD=password SITE_EMAIL=i@camerongreen.org ./scripts/create_site.sh
       
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: phpunit
