# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers
      - image: circleci/mysql:latest

    working_directory: ~/project

    dependencies:
      pre:
        - sudo apt-get update
        - sudo apt-get install mysql-client
        - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        - php composer-setup.php
        - php -r "unlink('composer-setup.php');"
        - php composer.phar self-update
        - sudo mv composer.phar /usr/local/bin/composer
        - sudo composer self-update
      post:
        - sudo cp ~/project/.circleci/config/alq.conf /etc/apache2/sites-available
        - sudo a2ensite alq
        - sudo service apache2 restart

    steps:
      - checkout

      # Get composer working.

      - run: composer install --prefer-dist

      - run: GIT_DIR=~/project ADMIN=testadmin DB_USER=root DB_NAME=circle_test DB_HOST=127.0.0.1 CIRCLECI=1 SITE_EMAIL=i@camerongreen.org ./scripts/create_site.sh

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: phpunit
