<?php
/**
 * @file
 * Provides misc functions, hooks etc
 */

/**
 * Implements hook_form_alter().
 */
function alq_misc_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'contact_site_form') {
      $form['#submit'][] = '_contact_site_form_submit';
  }
}


function _contact_site_form_submit(&$form, &$form_state) {
  $form_state['redirect'] = 'contact';
  drupal_set_message("Thank you for contacting us, we will reply to your email as soon as possible.");
}
