<?php
/**
 * @file
 * Provides the ability to store, administer and email members of parliament
 */

include_once(drupal_get_path('module', 'alq_mps') . '/alq_mps_install.inc');

define('ALQ_ELECTORATES_TABLE', 'alq_electorates');
define('ALQ_NODE_REF_TABLE', 'field_data_field_parent_article');

$GLOBALS['mpsFields'] = [
  'id' => NULL,
  'name' => NULL,
  'family_name' => NULL,
  'given_names' => NULL,
  'preferred_name' => NULL,
  'title' => NULL,
  'qualifications' => NULL,
  'position' => NULL,
  'party' => NULL,
  'electorate' => NULL,
  'type' => NULL,
  'comments' => NULL,
  'created' => NULL,
  'changed' => NULL,
];

$GLOBALS['officeFields'] = [
  'id' => NULL,
  'electorate' => NULL,
  'type' => NULL,
  'state' => NULL,
  'address' => NULL,
  'postcode' => NULL,
  'email' => NULL,
  'phone' => NULL,
  'toll_free_phone' => NULL,
  'fax' => NULL,
  'created' => NULL,
  'changed' => NULL,
];

/**
 * Implements hook menu
 */
function alq_mps_menu() {
  $items['alq-mps'] = [
    'page callback' => 'alq_mps_search',
    'access callback' => 'user_access',
    'access arguments' => ['access email campaigns'],
  ];
  $items['alq-mps/details'] = [
    'page callback' => 'alq_mps_details',
    'access callback' => 'user_access',
    'access arguments' => ['access email campaigns'],
  ];
  return $items;
}

/**
 * Menu callback for mps search
 */
function alq_mps_search($search) {
  if (strlen($search) > 2) {
    // first we get a listing of electorates which map
    // to the postcode or suburb
    $query = db_select(ALQ_ELECTORATES_TABLE, 'ele');
    $query->join('field_data_field_electorate', 'fel', 'ele.state_district = fel.field_electorate_value');
    $query->join('node', 'n', 'n.nid = fel.entity_id');
    $query->condition(
      db_or()
        ->condition('ele.locality', '%' . db_like($search) . '%', 'LIKE')
        ->condition('ele.postcode', db_like($search) . '%', 'LIKE')
    );
    $query->condition('fel.entity_type', 'node', '=')
      ->fields('n', [
        'title',
        'nid'
      ])
      ->fields('ele', [
        'locality',
        'state_district',
        'postcode'
      ])
    ;

    $query->orderBy('ele.locality', 'ASC');
    $query->groupBy('ele.locality');
    $query->groupBy('ele.postcode');
    $query->groupBy('n.nid');

    $results = $query->execute()->fetchAll();

    return drupal_json_output($results);
  }

  drupal_json_output([]);
}

/**
 * Menu callback for mps details
 */
function alq_mps_details($nids) {
  $nodes = node_load_multiple($nids);
  drupal_json_output($nodes);
}

/**
}

/**
 * Menu callback for editing an individual mp
 */
function alq_mps_get($id) {
  $mp = node_load($id);
  return $mp;
}

function alq_mps_show_email_campaign($node) {
  if ($cid = alq_mps_has_email_campaign($node->nid)) {
    drupal_add_css('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css', array('type' => 'external'));
    drupal_add_js('//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js', array('type' => 'external'));
    drupal_add_js(drupal_get_path('module', 'alq_mps') . '/theme/alq-mps.js');
    $cnode = node_load($cid);
    $form = drupal_get_form('alq_mps_email_form', $cnode);
    return drupal_render($form);
  }
}

function alq_mps_has_email_campaign($nid) {
  $query = db_select(ALQ_NODE_REF_TABLE, 'nrf');
  $query->condition(
    db_or()
      ->condition('nrf.entity_type', 'node', '=')
      ->condition('nrf.field_parent_article_nid', $nid, '=')
  )->fields('nrf', [
    'entity_id'
  ]);

  $result = $query->execute();

  return $result->fetchField(0);
}

function alq_mps_email_form($form, &$form_state, $cnode) {
  $form['id'] = [
    '#type' => 'hidden',
    '#required' => TRUE,
    '#default_value' => $cnode->nid,
  ];

  $form['search'] = [
    '#title' => 'Search for your MP',
    '#type' => 'fieldset',
    '#collapsible' => FALSE
  ];
  $form['search']['suburb'] = [
    '#type' => 'textfield',
    '#title' => t('Suburb or Post Code'),
    '#required' => TRUE,
    '#attributes' => [
      'autocomplete' => 'off'
    ]
  ];

  $form['subject'] = [
    '#type' => 'textfield',
    '#title' => t('Subject'),
    '#required' => TRUE,
    '#default_value' => $cnode->title,
  ];
  $form['body'] = [
    '#type' => 'textarea',
    '#title' => t('Email body'),
    '#required' => TRUE,
    '#default_value' => $cnode->field_body[LANGUAGE_NONE][0]["value"],
  ];
  $form['name'] = [
    '#type' => 'textfield',
    '#title' => t('Your name'),
    '#required' => TRUE
  ];
  $form['email'] = [
    '#type' => 'textfield',
    '#title' => t('Your email'),
    '#required' => TRUE
  ];
  $form['spam'] = [
    '#type' => 'checkbox',
    '#title' => t('Would you like to join the Animal Liberation Qld email list'),
    '#required' => TRUE
  ];
  $form['submit'] = [
    '#type' => 'submit',
    '#value' => t('Send'),
  ];

  return $form;
}
