#
# Docker build for alq.org.au
#

db:
    container_name: alq_db
    build: .
    dockerfile: Dockerfile-db
    ports:
        - "26906:3306"
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql

web:
    container_name: alq_web
    build: .
    ports:
        - "26980:80"
        - "5000:5000"
    volumes:
        - ../../public_html:/var/www/html
        - ..:/var/www/alq
        - ../../sql:/var/www/sql
    links:
        - db:mysql
