#
# Docker build for alq.org.au
#

db:
    container_name: alq_db
    build: .
    dockerfile: Dockerfile-db
    ports:
        - "26906:3306"
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql

web:
    container_name: alq_web
    build: .
    ports:
        - "26980:80"
    volumes:
        - ../../public_html:/var/www/html
        - ..:/var/www/alq
        - ../../sql:/var/www/sql
    links:
        - db:mysql

selenium-fx:
    container_name: alq_selenium_fx
    image: selenium/standalone-firefox-debug:2.48.2
    ports:
        - "26944:4444"
        - "26959:5900"
    restart: always
    links:
        - web

test-runner:
    container_name: alq_test_runner
    build: .
    dockerfile: Dockerfile-test
    tty: true
    volumes:
        - ../test:/var/www/test
    links:
        - selenium-fx
