#
# Docker build for alq.org.au
#

web:
    build: .
    ports:
        - "26980:80"
    volumes:
        - ../../public_html:/var/www/html
        - ..:/var/www/alq
        - ../../sql:/var/www/sql
    links:
        - db:mysql
db:
    build: .
    dockerfile: Dockerfile-db
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql
