#
# Docker build for alq.org.au
#

web:
    build: .
    ports:
        - "26980:80"
    volumes:
        - ../../public_html:/var/www/html
        - ..:/var/www/alq
        - ../../sql:/var/www/sql
    links:
        - db:mysql
db:
    build: .
    dockerfile: Dockerfile-db
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql
selenium-fx:
    image: selenium/standalone-firefox-debug:2.47.1
    ports:
        - "26944:4444"
    restart: always
test-runner:
    build: .
    dockerfile: Dockerfile-test
    tty: true
    volumes:
        - ../test:/var/www/test
    links:
        - selenium-fx
