#
# Docker build for alq.org.au
# Use 269 prefix for ports
#
# You will need a back up of the database in gz form before proceeding.
#
# First time run with:
#   MYSQL_ROOT_PASSWORD=secret MYSQL_DATABASE=alq_db MYSQL_USER=alq MYSQL_PASSWORD=secret docker-compose up
#   where root password is anything you want, and mysql user/password/db is from your settings.php file
#
# Subsequently you don't need the db credentials so just the usual:
#   docker-compose up
#
# To create the empty site:
#   docker-compose run -e DEFAULT_SITE_EMAIL="alq@example.com" web ../alq/scripts/create_site.sh
#
# To population the database with a mysql dump get into the web container, copy your
# mysqldump file into the sql directory as outlines in web volumes below:
#   docker-compose run -e DEFAULT_SITE_EMAIL="alq@example.com" web ../alq/scripts/import_prod_db.sh
#

web:
    build: .
    ports:
        - "26980:80"
    volumes:
        - ../../public_html:/var/www/html
        - ..:/var/www/alq
        - ../../sql:/var/www/sql
    links:
        - db:mysql
db:
    build: .
    dockerfile: Dockerfile-db
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql
