#
# Docker build for alq.org.au
#

db:
    container_name: alq_db
    build: .
    dockerfile: Dockerfile-db
    ports:
        - "26906:3306"
    environment:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    volumes:
        - /var/lib/mysql

web:
    container_name: alq_web
    build: .
    environment:
        - XDEBUG_CONFIG
        - PHP_IDE_CONFIG=serverName=alq.test
    ports:
        - "26980:80"
    volumes:
        # Linux
        #- ../../:/var/www/html
        # OSX
        - ../../:/var/www/html:cached
    links:
        - db:mysql
