#
# Docker build for alq.org.au
#
version: '3.7'

services:
  db:
    container_name: ${MYSQL_HOST}
    build:
      context: ./
      dockerfile: Dockerfile-db
    ports:
      - "26906:3306"
    networks:
      - ${COMPOSE_PROJECT_NAME}_net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - /var/lib/mysql

  web:
    container_name: alq-web
    build:
      context: .
    environment:
      ADMIN: ${ADMIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      COLUMNS: 160
      DB_DRIVER: mysql
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_NAME_RODEOS: ${MYSQL_DATABASE_RODEOS}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_USER: ${MYSQL_USER}
      PHP_IDE_CONFIG: serverName=${HOST_NAME}
      XDEBUG_CONFIG: "remote_host=${REMOTE_HOST} idekey=${IDEKEY}"
      TZ: ${TIMEZONE}
    networks:
      - ${COMPOSE_PROJECT_NAME}_net
    ports:
      - "26980:80"
    volumes:
      # Linux
      - ../../:/var/www/html:z
      - ./config/php.ini:/usr/local/etc/php/php.ini:z
      - ./config/.bashrc:/root/.bashrc:z
      # OSX
      #- ../../:/var/www/html:cached
    depends_on:
      - db

networks:
  alq_net:
