#
# Docker test containers for alq.org.au
#

selenium-fx:
    container_name: alq-selenium-fx
    image: selenium/standalone-firefox-debug:3.10
    ports:
        - "26944:4444"
        - "26959:5900"
    restart: always
    links:
        - web

test-runner:
    container_name: alq-test-runner
    build: .
    dockerfile: Dockerfile-test
    tty: true
    volumes:
        - ../test:/var/www/test
    links:
        - selenium-fx
