# Docker build for alq.org.au
FROM debian:buster

# Install libraries and utils needed.
RUN apt-get update \
    && apt install -y curl firefox-esr libglib2.0 libnss3 libx11-6 procps vim

# Install Chrome.
RUN curl -LO https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y ./google-chrome-stable_current_amd64.deb

# install node
RUN curl -sL https://deb.nodesource.com/setup_11.x | bash -
RUN apt install -y nodejs

WORKDIR /var/www/test

