#
# Docker build for alq.org.au
#
version: '3.7'

services:
  db:
    container_name: alq-db
    build:
      context: .
      dockerfile: Dockerfile-db
    networks:
      - alq_network
    ports:
      - "26906:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - /var/lib/mysql

  web:
    container_name: alq-web
    build:
      context: .
    environment:
      - XDEBUG_CONFIG
      - PHP_IDE_CONFIG=serverName=alq.test
    networks:
      - alq_network
    ports:
      - "26980:80"
    volumes:
      # Linux
      - ../../:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      # OSX
      #- ../../:/var/www/html:cached
    depends_on:
      - db

networks:
  alq_network:
