#
# Docker test containers for alq.org.au
#

test:
    container_name: alq-test
    build: .
    dockerfile: Dockerfile-test
    tty: true
    volumes:
        - ../test:/var/www/test
        - ../tmp:/tmp/screenshots
    links:
        - web
