<?php
/**
 * @file
 * Provides functions for the animal liberation donate form
 */
function alq_forms_menu() {
  $items['donate/submission'] = [
    'page callback' => 'alq_forms_submission',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  ];
  $items['membership/submission'] = [
    'page callback' => 'alq_forms_submission',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  ];
  return $items;
}

/**
 * Callback handler for form submission
 */
function alq_forms_submission() {
  global $user;
  $node = alq_forms_webform_loader('Donations form', 'webform');

  try {
    $data = alq_forms_parse_post_fields();

    $submission = (object) [
      'sid' => NULL,
      'nid' => $node->nid,
      'uid' => $user->uid,
      'submitted' => REQUEST_TIME,
      'remote_addr' => ip_address(),
      'is_draft' => FALSE,
      'data' => $data,
    ];

    module_load_include('inc', 'webform', 'includes/webform.submissions');
    $sid = webform_submission_insert($node, $submission);
    webform_submission_send_mail($node, $submission);
    $returnVal['type'] = 'success';
    $returnVal['message'] = 'sid:' . $sid;
  } catch (Exception $e) {
    $returnVal['type'] = 'error';
    $returnVal['message'] = $e->getMessage();
  }

  return drupal_json_output($returnVal);
}


function alq_forms_webform_loader($title, $type) {
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('type', $type)
    ->propertyCondition('title', $title)
    ->range(0, 1)
    ->execute();

  if (!empty($entities['node'])) {
    return node_load(array_shift(array_keys($entities['node'])));
  }

  return FALSE;
}

function alq_forms_parse_post_fields() {
  $data = [];

  // these need to be in the same order as the database table
  // see - drush sqlq 'SELECT cid, form_key, name FROM webform_component WHERE nid = :webform_nid;'
  $fields = [
    'donationType',
    'amount',
    'membership',
    'givenName',
    'familyName',
    'email',
    'phone',
    'address1',
    'address2',
    'suburb',
    'postcode',
    'occupation',
    'membershipType',
    'title',
    'newsletter',
    'volunteering',
    'spam',
    'subject',
  ];

  $required = [
    'donationType',
    'amount',
    'subject',
  ];

  for ($i = 0, $l = count($fields); $i < $l; $i++) {
    $value = array_key_exists($fields[$i], $_POST) ? $_POST[$fields[$i]] : NULL;

    if (in_array($fields[$i], $required) && ($value === NULL)) {
      throw new Exception('Missing required field - ' . $fields[$i]);
    }

    $data[$i + 1] = [
      $value,
    ];
  }

  return $data;
}


/**
 * Implements hook_block_info().
 */
function alq_forms_block_info() {
  return [
    "alq_donation_form" => [
      "info" => t("ALQ Donation Form"),
    ],
    "alq_membership_form" => [
      "info" => t("ALQ Membership Form"),
    ],
  ];
}

/**
 * Implements hook_block_view().
 */
function alq_forms_block_view($delta = "") {
  global $base_url, $conf;
  $block = NULL;

  drupal_add_css(drupal_get_path('module', 'alq_forms') . '/bower_components/form.validation/dist/css/formValidation.css');
  drupal_add_css(drupal_get_path('module', 'alq_forms') . '/theme/styles.css');

  drupal_add_js(drupal_get_path('module', 'alq_forms') . '/bower_components/form.validation/dist/js/formValidation.min.js', ['scope' => 'footer']);
  drupal_add_js(drupal_get_path('module', 'alq_forms') . '/bower_components/form.validation/dist/js/framework/bootstrap.min.js', ['scope' => 'footer']);

  $paypalUrl = variable_get("uc_paypal_wpp_server", "https://api-3t.sandbox.paypal.com/nvp");
  if (stripos($paypalUrl, 'sandbox') === FALSE) {
    $url = 'https://www.paypal.com/cgi-bin/webscr';
    $business = $conf['paypal_id'];
  }
  else {
    $url = 'https://www.sandbox.paypal.com/cgi-bin/webscr';
    $business = $conf['paypal_email'];
  }

  switch ($delta) {
    case "alq_donation_form":
      drupal_add_js(drupal_get_path('module', 'alq_forms') . '/theme/donation-form.js');
      $block["subject"] = t("Donations");

      $redirect_url_cancel = $base_url . '/donate';
      $redirect_url = $base_url . '/thanks';

      $block["content"] = theme("alq_donation_form", [
        'action' => $url,
        'business' => $business,
        'redirect_url' => $redirect_url,
        'redirect_url_cancel' => $redirect_url_cancel,
      ]);
      break;
    case "alq_membership_form":
      drupal_add_js(drupal_get_path('module', 'alq_forms') . '/theme/membership-form.js');
      $block["subject"] = t("Membership");

      $redirect_url_cancel = $base_url . '/membership';
      $redirect_url = $base_url . '/thanks';

      $block["content"] = theme("alq_membership_form", [
        'action' => $url,
        'business' => $business,
        'redirect_url' => $redirect_url,
        'redirect_url_cancel' => $redirect_url_cancel,
      ]);
      break;
  }

  return $block;
}

/**
 * Implements hook_theme();
 */
function alq_forms_theme() {
  return [
    "alq_donation_form" => [
      "template" => "theme/donation-form",
      "variables" => [
        'action' => NULL,
        'business' => NULL,
        'redirect_url' => NULL,
        'redirect_url_cancel' => NULL,
      ],
    ],
    "alq_membership_form" => [
      "template" => "theme/membership-form",
      "variables" => [
        'action' => NULL,
        'business' => NULL,
        'redirect_url' => NULL,
        'redirect_url_cancel' => NULL,
      ],
    ],
  ];
}


/**
 * Implements hook_cron().
 */
function alq_forms_cron() {
  $my_module = 'alq_forms';
  $seconds_in_day = 24 * 60 * 60;
  $days_to_email = 7; // If no submissions since this time email.

  // Only run once a day.
  if ((time() - $seconds_in_day) >= variable_get('cron_last', 0)) {
    $nid = 254; // Donations form.

    $last_updated = alq_forms_webform_last_submission($nid);

    // If the last submission was more than a week ago, email admin and log
    // in watchdog.
    if ($last_updated < (time() - ($days_to_email * $seconds_in_day))) {
      watchdog(WATCHDOG_ERROR, "No submissions in last $days_to_email for form $nid");

      $node_url = "http://alq.org.au/node/${nid}";

      $from = variable_get('system_mail', 'info@alq.org.au');
      $message = [
        'id' => $my_module,
        'from' => $from,
        'to' => 'i@camerongreen.org',
        'subject' => 'alq.org.au: No donations in last week',
        'body' => "Form to check: <a href=\"${node_url}\">${node_url}</a>\n",
        'headers' => [
          'From' => $from,
          'Sender' => $from,
          'Return-Path' => $from,
        ],
      ];

      $system = drupal_mail_system($my_module, 'webform_submissions_check');
      $system->mail($message);
    }
  }
}


/**
 * Last date webform had submission.
 *
 * @param int $nid
 *   Nid of webform to check.
 *
 * @return array
 *   Details.
 *
 */
function alq_forms_webform_last_submission($nid) {
  $query = db_select('node', 'n');
  $query->join('webform_submissions', 'w', 'n.nid = w.nid');
  $query->addExpression('MAX(w.completed)', 'max_completed');
  $query->groupBy('n.nid');
  $query->condition('n.nid', $nid);
  $result = $query->execute();
  return $result->fetchField();
}
